'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),{webcrypto}=require('node:crypto');
const incident=require('../assets/incident-triage-core.js'),cases=require('../assets/incident-triage-workspace.js'),firewall=require('../assets/firewall-review-core.js'),changes=require('../assets/firewall-change-core.js');
function harness(language='en'){
  const elements=new Map(),listeners={},jobs=[],blobs=[];
  const element=id=>{if(!elements.has(id)){let value='';const el={files:[],checked:false,dataset:{},textContent:'',innerHTML:'',hidden:false,disabled:false,handlers:{},setAttribute(k,v){this[k]=v;},querySelectorAll(){return[];},addEventListener(name,fn){this.handlers[name]=fn;},focus(){},scrollIntoView(){},click(){const result=this.handlers.click?.();if(result?.then)jobs.push(result);return result;}};Object.defineProperty(el,'value',{get:()=>value,set:v=>{value=v;if(v===''&&['it-files','cc-add-files','it-resume-file'].includes(id))el.files=[];}});elements.set(id,el);}return elements.get(id);};
  const document={documentElement:{lang:language},getElementById:element,querySelectorAll:()=>[],addEventListener(name,fn){(listeners[name]??=[]).push(fn);},dispatchEvent(e){for(const fn of listeners[e.type]||[])fn(e);},body:{append(){}},createElement:()=>({click(){},remove(){}})};
  class Worker{postMessage(data){const job=new Promise(resolve=>queueMicrotask(()=>{if(!this.cancelled){try{this.onmessage({data:data.before?{result:changes.review(data.before,data.after,data.scenarios,data.delta)}:data.restoreCase?{restored:cases.restoreCase(data.restoreCase,incident)}:{result:incident.analyze(data)}});}catch(e){this.onmessage({data:{error:e.code||'unexpected'}});}}resolve();}));jobs.push(job);}terminate(){this.cancelled=true;}}
  const context=vm.createContext({window:null,document,IncidentTriage:incident,FirewallReview:firewall,FirewallChangeReview:changes,Blob,Event,URL:{createObjectURL(b){blobs.push(b);return 'blob:local';},revokeObjectURL(){}},crypto:webcrypto,TextEncoder,TextDecoder,Worker,setTimeout:fn=>{queueMicrotask(fn);return 0;},clearTimeout(){}});context.window=context;
  element('fw-vendor').value='auto';element('fw-severity').value='all';
  for(const file of ['firewall-review-demo.js','firewall-change-ui.js','firewall-review.js','connected-case-core.js','incident-triage-demo.js','incident-triage-platform-demos.js','incident-triage-workspace.js','incident-triage-ui.js','connected-case-ui.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets',file),'utf8'),context);
  for(const id of ['it-form','fw-form'])element(id).requestSubmit=()=>jobs.push(element(id).handlers.submit({preventDefault(){}}));
  async function flush(){let count=-1;while(count!==jobs.length){count=jobs.length;await Promise.all(jobs);}await Promise.resolve();}
  const json=async()=>{element('it-export-json').click();return JSON.parse(await blobs.at(-1).text());};
  return {element,document,context,flush,json,async demo(){element('cc-demo').click();await flush();},select(){const f=context.ConnectedCase.summarize(context.IncidentCaseWorkspace.current()).flows[0];element('cc-flows').handlers.click({target:{closest:selector=>selector==='[data-cc-select]'?{dataset:{ccSelect:f.key}}:null}});return f;},stage(){for(const [id,value]of Object.entries({'cc-from':'corp','cc-to':'servers','cc-before-scope':'root','cc-after-scope':'root','cc-expected':'permit'}))element(id).value=value;element('cc-stage').click();},async review(){const before=await nativeConfig(false),after=await nativeConfig(true);element('fw-vendor').value='fortinet';element('fw-before').value=before;element('fw-input').value=after;await element('fw-form').handlers.submit({preventDefault(){}});await flush();},async resume(saved){const bytes=new TextEncoder().encode(JSON.stringify(saved));element('it-resume-file').files=[{size:bytes.length,arrayBuffer:async()=>bytes}];await element('it-resume-file').handlers.change();await flush();}};
}
async function nativeConfig(after){return 'config firewall address\nedit "CLIENT"\nset subnet 10.20.9.25 255.255.255.255\nnext\nedit "APP"\nset subnet 10.30.0.10 255.255.255.255\nnext\nend\nconfig firewall service custom\nedit "HTTPS"\nset tcp-portrange 443\nnext\nend\nconfig firewall policy\nedit 1\nset name "App HTTPS"\nset srcintf "corp"\nset dstintf "servers"\nset srcaddr "CLIENT"\nset dstaddr "APP"\nset service "HTTPS"\nset schedule "always"\nset action '+(after?'accept':'deny')+'\nset logtraffic all\nnext\nend';}
test('Complete connected investigation → policy → retest → save/reopen workflow runs in EN/RO/FR',async()=>{
  for(const language of ['en','ro','fr']){const ui=harness(language);await ui.demo();assert.equal(ui.element('it-status').dataset.error,'false');assert.equal(ui.element('cc-workspace').hidden,false);const initial=await ui.json();assert.equal(initial.events.length,4);assert.equal(initial.synthetic,true);const f=ui.select();assert.equal(f.candidates.length,2);
    ui.element('cc-stage').click();assert.equal(ui.element('fc-enable').checked,false);ui.stage();assert.equal(ui.element('fc-enable').checked,true);assert.equal(ui.element('cc-return').hidden,false);assert.ok(ui.element('fc-rows').innerHTML.includes('51000'));await ui.review();assert.equal(ui.element('fw-status').dataset.error,'false');let saved=await ui.json();assert.equal(saved.connectedCase.reviews.length,1);assert.equal(saved.connectedCase.reviews[0].result.flows[0].after.verdict,'permit');
    ui.element('cc-demo-after').click();await ui.flush();saved=await ui.json();assert.equal(saved.events.length,7);assert.equal(saved.sources.length,2);assert.equal(ui.context.ConnectedCase.summarize(saved).comparisons[0].after.synPairObserved,true);assert.ok(ui.element('cc-comparison').innerHTML.includes('true'));ui.element('it-export-html').click();const html=await ui.context.ConnectedCaseUI.html(saved);assert.ok(html.includes('App HTTPS'));assert.ok(html.includes('source-1:1'));ui.element('it-clear').click();assert.equal(ui.element('cc-workspace').hidden,true);await ui.resume(saved);assert.equal(ui.element('it-status').dataset.error,'false');const restored=await ui.json();assert.equal(restored.events.length,7);assert.equal(restored.connectedCase.reviews[0].recomputed,true);assert.equal(restored.connectedCase.reviews[0].result.flows[0].after.verdict,'permit');assert.equal(restored.connectedCase.id,saved.connectedCase.id);
  }
});
test('A new investigation rejects results from an earlier staged case',async()=>{const ui=harness();await ui.demo();ui.select();ui.stage();const old=(await ui.json()).connectedCase.id;await ui.demo();assert.notEqual((await ui.json()).connectedCase.id,old);await ui.review();assert.equal((await ui.json()).connectedCase.reviews.length,0);});
test('Changing an evidence tuple in the scenario editor removes its association',async()=>{const ui=harness();await ui.demo();ui.select();ui.stage();ui.element('fc-rows').handlers.input({target:{dataset:{fcField:'sourceIP',fcRow:'0'},value:'10.20.9.26'}});await ui.review();assert.equal((await ui.json()).connectedCase.reviews.length,0);});
test('Malformed append and exceeded limits preserve the original case and attached policy decisions',async()=>{const ui=harness();await ui.demo();ui.select();ui.stage();await ui.review();const saved=await ui.json(),bad=new TextEncoder().encode('{bad');await ui.context.IncidentCaseWorkspace.appendEvidence([{name:'bad.json',size:bad.length,arrayBuffer:async()=>bad}],'after');await ui.flush();assert.equal(ui.element('it-status').dataset.error,'true');assert.equal((await ui.json()).connectedCase.reviews.length,1);assert.equal((await ui.json()).events.length,saved.events.length);await ui.context.IncidentCaseWorkspace.appendEvidence([{name:'large.json',size:incident.MAX_BYTES}],'before');assert.ok(ui.element('it-status').textContent.includes('10 MiB'));assert.equal((await ui.json()).sources.length,1);});
test('Language changes preserve context and evidence, and produce language-specific Store links',async()=>{const ui=harness();await ui.demo();ui.select();ui.stage();ui.document.dispatchEvent({type:'site:languagechange',detail:{language:'fr'}});assert.equal(ui.element('cc-from').value,'corp');assert.equal(ui.element('cc-expected').value,'permit');assert.equal(ui.element('cc-firewall-link').href,'store.html?lang=fr#firewall-security-hardening-toolkit');assert.ok(ui.element('cc-counts').textContent.includes('Connexions'));await ui.review();assert.equal((await ui.json()).connectedCase.reviews.length,1);});
