'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),{webcrypto}=require('node:crypto');
const core=require('../assets/incident-triage-core.js');
async function harness(language='en'){
  const elements=new Map(),blobs=[],listeners={},pending=[];
  const element=id=>{if(!elements.has(id)){let value='';const el={files:[],checked:false,dataset:{},textContent:'',innerHTML:'',hidden:false,disabled:false,handlers:{},addEventListener(name,fn){this.handlers[name]=fn;},setAttribute(){}};Object.defineProperty(el,'value',{get:()=>value,set:v=>{value=v;if(id==='it-files'&&v==='')el.files=[];}});elements.set(id,el);}return elements.get(id);};
  const document={documentElement:{lang:language},getElementById:element,querySelectorAll:()=>[],addEventListener(name,fn){(listeners[name]??=[]).push(fn);},dispatchEvent(e){for(const fn of listeners[e.type]||[])fn(e);},body:{append(){}},createElement:()=>({click(){},remove(){}})};
  class Worker{postMessage(data){const p=new Promise(resolve=>queueMicrotask(()=>{if(!this.cancelled){try{this.onmessage({data:{result:core.analyze(data)}});}catch(e){this.onmessage({data:{error:e.code||'unexpected'}});}}resolve();}));pending.push(p);}terminate(){this.cancelled=true;}}
  const context=vm.createContext({window:null,document,IncidentTriage:core,Blob,URL:{createObjectURL(b){blobs.push(b);return 'blob:local';},revokeObjectURL(){}},crypto:webcrypto,TextEncoder,TextDecoder,Worker,setTimeout:fn=>{queueMicrotask(fn);return 0;},clearTimeout(){}});context.window=context;
  for(const file of ['incident-triage-demo.js','incident-triage-ui.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets',file),'utf8'),context);
  let run; element('it-form').requestSubmit=()=>run=element('it-form').handlers.submit({preventDefault(){}});
  return {element,context,document,blobs,async demo(){element('it-demo').handlers.click();await run;await Promise.all(pending);},async analyze(){await element('it-form').handlers.submit({preventDefault(){}});await Promise.all(pending);},async export(kind){element('it-export-'+kind).handlers.click();return blobs.at(-1).text();}};
}
test('Full local investigation lab works in EN/RO/FR with hashes and all export types',async()=>{
  for(const lang of ['en','ro','fr']){const ui=await harness(lang);await ui.demo();assert.equal(ui.element('it-status').dataset.error,'false');assert.equal(ui.element('it-results').hidden,false);const r=JSON.parse(await ui.export('json'));assert.equal(r.summary.unique,16);assert.equal(r.summary.high,4);assert.equal(r.sources[0].sha256.length,64);assert.equal(r.synthetic,true);assert.equal(r.processLinks.length,1);const actual=await webcrypto.subtle.digest('SHA-256',new TextEncoder().encode(ui.element('it-input').value));assert.equal(r.sources[0].sha256,Buffer.from(actual).toString('hex'));assert.ok((await ui.export('html')).includes('Content-Security-Policy'));assert.ok((await ui.export('csv')).includes('192.0.2.25'));assert.equal(JSON.parse(await ui.export('events')).events.length,16);}
});
test('Analyst decisions/notes and case fields persist through language/filter changes and exports',async()=>{const ui=await harness('ro');await ui.demo();const r=JSON.parse(await ui.export('json')),id=r.findings[0].id;ui.element('it-findings').handlers.change({target:{dataset:{itReview:id},value:'explained'}});ui.element('it-findings').handlers.input({target:{dataset:{itNote:id},value:'Authorized laboratory test'}});ui.element('it-case').value='CASE-42';ui.element('it-analyst').value='Analyst A';ui.document.dispatchEvent({type:'site:languagechange',detail:{language:'fr'}});ui.element('it-priority').value='low';ui.element('it-priority').handlers.change();const exported=JSON.parse(await ui.export('json'));assert.equal(exported.case.reference,'CASE-42');assert.equal(exported.analystReviews.find(n=>n.findingId===id).status,'explained');assert.equal(exported.analystReviews.find(n=>n.findingId===id).notes,'Authorized laboratory test');assert.ok((await ui.export('html')).includes('Authorized laboratory test'));assert.equal(exported.findings.length,10);});
test('Editing or clearing evidence invalidates prior results and reviews',async()=>{const ui=await harness();await ui.demo();ui.element('it-input').value='{bad';ui.element('it-input').handlers.input();assert.equal(ui.element('it-results').hidden,true);await ui.analyze();assert.equal(ui.element('it-status').dataset.error,'true');ui.element('it-clear').handlers.click();assert.equal(ui.element('it-input').value,'');assert.equal(ui.element('it-results').hidden,true);assert.equal(ui.element('it-status').textContent,'');});
test('Malformed, oversized and ambiguous evidence is rejected without starting a misleading review',async()=>{const ui=await harness();await ui.demo();ui.element('it-files').files=[{name:'a.json',size:10}];await ui.analyze();assert.equal(ui.element('it-status').dataset.error,'true');assert.equal(ui.element('it-results').hidden,true);ui.element('it-input').value='';ui.element('it-files').files=[{name:'a.json',size:core.MAX_BYTES+1}];await ui.analyze();assert.ok(ui.element('it-status').textContent.includes('10 MiB'));});
test('Local file import hashes original UTF-16 bytes and distinguishes unsupported EVTX',async()=>{const ui=await harness();const payload=JSON.stringify([{eventId:1102,timestamp:'2026-10-04T08:00:00Z',host:'WS',provider:'Microsoft-Windows-Security-Auditing',channel:'Security',data:{}}]);const bytes=Buffer.concat([Buffer.from([255,254]),Buffer.from(payload,'utf16le')]);ui.element('it-files').files=[{name:'evidence.json',size:bytes.length,arrayBuffer:async()=>bytes}];await ui.analyze();const r=JSON.parse(await ui.export('json'));assert.equal(r.summary.high,1);assert.equal(r.sources[0].bytes,bytes.length);assert.equal(r.sources[0].sha256,Buffer.from(await webcrypto.subtle.digest('SHA-256',bytes)).toString('hex'));const binary=Buffer.from('ElfFile\0binary');ui.element('it-files').files=[{name:'Security.evtx',size:binary.length,arrayBuffer:async()=>binary}];await ui.analyze();assert.equal(ui.element('it-status').dataset.error,'true');assert.ok(ui.element('it-status').textContent.includes('EVTX'));});
test('Reusable event export round-trips and XSS payloads remain inert in UI/reports',async()=>{const ui=await harness();await ui.demo();const data=JSON.parse(await ui.export('events'));data.events[0].host='<img src=x onerror=alert(1)>';data.events[0].data.TargetUserName='<script>alert(1)</script>';ui.element('it-input').value=JSON.stringify(data);ui.element('it-input').handlers.input();await ui.analyze();assert.ok(ui.element('it-timeline').innerHTML.includes('&lt;img'));const html=await ui.export('html');assert.ok(!html.includes('<img src=x'));assert.ok(!html.includes('<script>alert(1)</script>'));assert.equal(JSON.parse(await ui.export('json')).summary.unique,16);});
test('CSV exports neutralize spreadsheet formulas and exports ignore display filters',async()=>{const ui=await harness();await ui.demo();const data=JSON.parse(await ui.export('events'));data.events[0].host='=HYPERLINK("https://example.invalid")';ui.element('it-input').value=JSON.stringify(data);ui.element('it-input').handlers.input();await ui.analyze();ui.element('it-host').value='LAB-SRV02';ui.element('it-host').handlers.change();const csv=await ui.export('csv');assert.ok(csv.includes("\"'=HYPERLINK"));assert.equal(JSON.parse(await ui.export('json')).events.length,16);});
