'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),{webcrypto}=require('node:crypto');
const core=require('../assets/incident-triage-core.js');
const workspace=require('../assets/incident-triage-workspace.js');
async function harness(language='en'){
  const elements=new Map(),blobs=[],listeners={},pending=[];
  const element=id=>{if(!elements.has(id)){let value='';const el={files:[],checked:false,dataset:{},textContent:'',innerHTML:'',hidden:false,disabled:false,handlers:{},addEventListener(name,fn){this.handlers[name]=fn;},setAttribute(){}};Object.defineProperty(el,'value',{get:()=>value,set:v=>{value=v;if(id==='it-files'&&v==='')el.files=[];}});elements.set(id,el);}return elements.get(id);};
  const document={documentElement:{lang:language},getElementById:element,querySelectorAll:()=>[],addEventListener(name,fn){(listeners[name]??=[]).push(fn);},dispatchEvent(e){for(const fn of listeners[e.type]||[])fn(e);},body:{append(){}},createElement:()=>({click(){},remove(){}})};
  class Worker{postMessage(data){const p=new Promise(resolve=>queueMicrotask(()=>{if(!this.cancelled){try{this.onmessage({data:data.restoreCase?{restored:workspace.restoreCase(data.restoreCase,core)}:{result:core.analyze(data)}});}catch(e){this.onmessage({data:{error:e.code||'unexpected'}});}}resolve();}));pending.push(p);}terminate(){this.cancelled=true;}}
  const context=vm.createContext({window:null,document,IncidentTriage:core,Blob,URL:{createObjectURL(b){blobs.push(b);return 'blob:local';},revokeObjectURL(){}},crypto:webcrypto,TextEncoder,TextDecoder,Worker,setTimeout:fn=>{queueMicrotask(fn);return 0;},clearTimeout(){}});context.window=context;
  for(const file of ['incident-triage-demo.js','incident-triage-platform-demos.js','incident-triage-workspace.js','incident-triage-ui.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets',file),'utf8'),context);
  let run; element('it-form').requestSubmit=()=>run=element('it-form').handlers.submit({preventDefault(){}});
  return {element,context,document,blobs,async demo(key){element(key?'it-demo-'+key:'it-demo').handlers.click();await run;await Promise.all(pending);},async analyze(){await element('it-form').handlers.submit({preventDefault(){}});await Promise.all(pending);},async resume(content){const bytes=new TextEncoder().encode(content);element('it-resume-file').files=[{size:bytes.length,arrayBuffer:async()=>bytes}];await element('it-resume-file').handlers.change();await Promise.all(pending);},async export(kind){element('it-export-'+kind).handlers.click();return blobs.at(-1).text();}};
}
test('Full local investigation lab works in EN/RO/FR with hashes and all export types',async()=>{
  for(const lang of ['en','ro','fr']){const ui=await harness(lang);await ui.demo();assert.equal(ui.element('it-status').dataset.error,'false');assert.equal(ui.element('it-results').hidden,false);const r=JSON.parse(await ui.export('json'));assert.equal(r.summary.unique,16);assert.equal(r.summary.high,4);assert.equal(r.sources[0].sha256.length,64);assert.equal(r.synthetic,true);assert.equal(r.processLinks.length,1);const actual=await webcrypto.subtle.digest('SHA-256',new TextEncoder().encode(ui.element('it-input').value));assert.equal(r.sources[0].sha256,Buffer.from(actual).toString('hex'));assert.ok((await ui.export('html')).includes('Content-Security-Policy'));assert.ok((await ui.export('csv')).includes('192.0.2.25'));assert.equal(JSON.parse(await ui.export('events')).events.length,16);}
});
test('Analyst decisions/notes and case fields persist through language/filter changes and exports',async()=>{const ui=await harness('ro');await ui.demo();const r=JSON.parse(await ui.export('json')),id=r.findings[0].id;ui.element('it-findings').handlers.change({target:{dataset:{itReview:id},value:'explained'}});ui.element('it-findings').handlers.input({target:{dataset:{itNote:id},value:'Authorized laboratory test'}});ui.element('it-case').value='CASE-42';ui.element('it-analyst').value='Analyst A';ui.document.dispatchEvent({type:'site:languagechange',detail:{language:'fr'}});ui.element('it-priority').value='low';ui.element('it-priority').handlers.change();const exported=JSON.parse(await ui.export('json'));assert.equal(exported.case.reference,'CASE-42');assert.equal(exported.analystReviews.find(n=>n.findingId===id).status,'explained');assert.equal(exported.analystReviews.find(n=>n.findingId===id).notes,'Authorized laboratory test');assert.ok((await ui.export('html')).includes('Authorized laboratory test'));assert.equal(exported.findings.length,10);});
test('Editing or clearing evidence invalidates prior results and reviews',async()=>{const ui=await harness();await ui.demo();ui.element('it-input').value='{bad';ui.element('it-input').handlers.input();assert.equal(ui.element('it-results').hidden,true);await ui.analyze();assert.equal(ui.element('it-status').dataset.error,'true');ui.element('it-clear').handlers.click();assert.equal(ui.element('it-input').value,'');assert.equal(ui.element('it-results').hidden,true);assert.equal(ui.element('it-status').textContent,'');});
test('Malformed, oversized and ambiguous evidence is rejected without starting a misleading review',async()=>{const ui=await harness();await ui.demo();ui.element('it-files').files=[{name:'a.json',size:10}];await ui.analyze();assert.equal(ui.element('it-status').dataset.error,'true');assert.equal(ui.element('it-results').hidden,true);ui.element('it-input').value='';ui.element('it-files').files=[{name:'a.json',size:core.MAX_BYTES+1}];await ui.analyze();assert.ok(ui.element('it-status').textContent.includes('10 MiB'));});
test('Local file import hashes original UTF-16 bytes and distinguishes unsupported EVTX',async()=>{const ui=await harness();const payload=JSON.stringify([{eventId:1102,timestamp:'2026-10-04T08:00:00Z',host:'WS',provider:'Microsoft-Windows-Security-Auditing',channel:'Security',data:{}}]);const bytes=Buffer.concat([Buffer.from([255,254]),Buffer.from(payload,'utf16le')]);ui.element('it-files').files=[{name:'evidence.json',size:bytes.length,arrayBuffer:async()=>bytes}];await ui.analyze();const r=JSON.parse(await ui.export('json'));assert.equal(r.summary.high,1);assert.equal(r.sources[0].bytes,bytes.length);assert.equal(r.sources[0].sha256,Buffer.from(await webcrypto.subtle.digest('SHA-256',bytes)).toString('hex'));const binary=Buffer.from('ElfFile\0binary');ui.element('it-files').files=[{name:'Security.evtx',size:binary.length,arrayBuffer:async()=>binary}];await ui.analyze();assert.equal(ui.element('it-status').dataset.error,'true');assert.ok(ui.element('it-status').textContent.includes('EVTX'));});
test('Reusable event export round-trips and XSS payloads remain inert in UI/reports',async()=>{const ui=await harness();await ui.demo();const data=JSON.parse(await ui.export('events'));data.events[0].host='<img src=x onerror=alert(1)>';data.events[0].data.TargetUserName='<script>alert(1)</script>';ui.element('it-input').value=JSON.stringify(data);ui.element('it-input').handlers.input();await ui.analyze();assert.ok(ui.element('it-timeline').innerHTML.includes('&lt;img'));const html=await ui.export('html');assert.ok(!html.includes('<img src=x'));assert.ok(!html.includes('<script>alert(1)</script>'));assert.equal(JSON.parse(await ui.export('json')).summary.unique,16);});
test('CSV exports neutralize spreadsheet formulas and exports ignore display filters',async()=>{const ui=await harness();await ui.demo();const data=JSON.parse(await ui.export('events'));data.events[0].host='=HYPERLINK("https://example.invalid")';ui.element('it-input').value=JSON.stringify(data);ui.element('it-input').handlers.input();await ui.analyze();ui.element('it-host').value='LAB-SRV02';ui.element('it-host').handlers.change();const csv=await ui.export('csv');assert.ok(csv.includes("\"'=HYPERLINK"));assert.equal(JSON.parse(await ui.export('json')).events.length,16);});

test('Every native platform lab runs in EN/RO/FR, exports evidence and round-trips platform metadata',async()=>{for(const lang of ['en','ro','fr']){for(const key of ['linux','fortinet','paloalto','checkpoint','cisco-ios','cisco-asa']){const ui=await harness(lang);await ui.demo(key);assert.equal(ui.element('it-status').dataset.error,'false',lang+':'+key);const r=JSON.parse(await ui.export('json'));assert.ok(r.events.length>1);assert.equal(r.synthetic,true);assert.equal(r.summary.missingTime,0);assert.equal(r.version,'2.1.0');assert.ok((await ui.export('html')).includes(r.events[0].provider));const exported=JSON.parse(await ui.export('events'));assert.equal(exported.schemaVersion,2);assert.ok(exported.events[0].platform);ui.element('it-input').value=JSON.stringify(exported);ui.element('it-input').handlers.input();ui.element('it-source-mode').value='auto';await ui.analyze();const reread=JSON.parse(await ui.export('json'));assert.deepEqual(reread.summary,r.summary);assert.deepEqual(reread.findings.map(f=>f.ruleId),r.findings.map(f=>f.ruleId));assert.equal(reread.synthetic,false);}}});
test('Context/source editing invalidates results, clear removes all context and native demo resets stale imports',async()=>{const ui=await harness();await ui.demo('cisco-ios');ui.element('it-year').value='2025';ui.element('it-year').handlers.input();assert.equal(ui.element('it-results').hidden,true);ui.element('it-source-mode').value='fortinet';ui.element('it-source-mode').handlers.change();await ui.analyze();assert.equal(ui.element('it-status').dataset.error,'true');await ui.demo('paloalto');assert.equal(ui.element('it-source-mode').value,'auto');assert.equal(ui.element('it-timezone').value,'+00:00');assert.equal(ui.element('it-year').value,'');ui.element('it-clear').handlers.click();for(const id of ['it-timezone','it-year','it-evidence-host'])assert.equal(ui.element(id).value,'');assert.equal(ui.element('it-source-mode').value,'auto');});
test('Platform display filters affect preview and preserve the full case report',async()=>{const ui=await harness();await ui.demo('cisco-ios');const cisco=JSON.parse(await ui.export('events'));await ui.demo('linux');const linux=JSON.parse(await ui.export('events'));ui.element('it-input').value=JSON.stringify({schema:'weownit.incident.events',schemaVersion:2,events:[...cisco.events,...linux.events]});ui.element('it-input').handlers.input();await ui.analyze();const all=JSON.parse(await ui.export('json'));ui.element('it-platform').value='linux';ui.element('it-platform').handlers.change();assert.ok(!ui.element('it-timeline').innerHTML.includes('LAB-CISCO-IOS'));assert.ok(ui.element('it-timeline').innerHTML.includes('LAB-LINUX'));assert.equal(JSON.parse(await ui.export('json')).summary.unique,15);assert.equal(all.platforms.filter(p=>p.events).length,2);assert.equal(JSON.parse(await ui.export('events')).events.length,15);});

test('Summary, evidence and next-step views work in all languages and update analyst decisions',async()=>{
  for(const lang of ['en','ro','fr']){const ui=await harness(lang);await ui.demo();assert.equal(ui.element('it-panel-summary').hidden,false);assert.equal(ui.element('it-panel-evidence').hidden,true);assert.ok(ui.element('it-summary').innerHTML.includes('16'));ui.element('it-view-evidence').handlers.click();assert.equal(ui.element('it-panel-evidence').hidden,false);const r=JSON.parse(await ui.export('json'));for(const f of r.findings)ui.element('it-findings').handlers.change({target:{dataset:{itReview:f.id},value:'explained'}});assert.equal(JSON.parse(await ui.export('json')).investigationOverview.states.explained,10);ui.element('it-view-steps').handlers.click();assert.equal(ui.element('it-panel-steps').hidden,false);assert.ok(!ui.element('it-next-steps').innerHTML.includes('PowerShell'));const html=await ui.export('html');assert.ok(html.includes(lang==='ro'?'Dovezi observate':lang==='fr'?'Preuves observées':'Observed evidence'));}
});
test('Saved cases reopen every platform with decisions, context, original timestamps, hashes and provenance',async()=>{
  for(const key of [null,'linux','fortinet','paloalto','checkpoint','cisco-ios','cisco-asa']){
    const ui=await harness('ro');await ui.demo(key);const saved=JSON.parse(await ui.export('json')),id=saved.findings[0].id;
    ui.element('it-findings').handlers.change({target:{dataset:{itReview:id},value:'followup'}});ui.element('it-findings').handlers.input({target:{dataset:{itNote:id},value:'Check ticket CHG-42'}});ui.element('it-case').value='CASE-42';ui.element('it-analyst').value='Analyst A';const content=await ui.export('json');ui.element('it-clear').handlers.click();await ui.resume(content);assert.equal(ui.element('it-status').dataset.error,'false',String(key)+': '+ui.element('it-status').textContent);const r=JSON.parse(await ui.export('json'));
    assert.deepEqual(r.summary,saved.summary);assert.deepEqual(r.sources,saved.sources);assert.deepEqual(r.importSummary,saved.importSummary);assert.deepEqual(r.events.map(e=>[e.uid,e.source,e.originalTimestamp,e.timestamp,e.contextApplied]),saved.events.map(e=>[e.uid,e.source,e.originalTimestamp,e.timestamp,e.contextApplied]));assert.equal(r.case.reference,'CASE-42');assert.equal(r.case.analyst,'Analyst A');assert.equal(r.analystReviews.find(n=>n.findingId===id).notes,'Check ticket CHG-42');assert.equal(r.analystReviews.find(n=>n.findingId===id).status,'followup');assert.equal(r.restoration.sourceHashesVerified,false);assert.equal(r.restoration.unmatchedReviews,0);assert.equal(r.synthetic,true);assert.equal(ui.element('it-input').value,'');assert.equal(ui.element('it-restored-notice').hidden,false);await ui.resume(await ui.export('json'));assert.equal(ui.element('it-status').dataset.error,'false');
  }
});
test('Malformed case reopening keeps the current case intact and oversized reports fail explicitly',async()=>{const ui=await harness();await ui.demo();const saved=await ui.export('json');await ui.resume('{bad');assert.equal(ui.element('it-status').dataset.error,'true');assert.equal(await ui.export('json'),saved);assert.equal(ui.element('it-results').hidden,false);ui.element('it-resume-file').files=[{size:workspace.MAX_CASE_BYTES+1}];await ui.element('it-resume-file').handlers.change();assert.ok(ui.element('it-status').textContent.includes('64 MiB'));assert.equal(ui.element('it-run').disabled,false);});
test('Entity selection uses exact event membership, preserves full exports and clears on new analysis',async()=>{const ui=await harness();await ui.demo();const report=JSON.parse(await ui.export('json')),index=workspace.entityIndex(report),position=index.findIndex(x=>x.type==='ip'&&x.value==='192.0.2.25');ui.element('it-entity-list').handlers.click({target:{closest:()=>({dataset:{itEntity:String(position)}})}});assert.equal(ui.element('it-panel-evidence').hidden,false);assert.equal(ui.element('it-entity-selection').hidden,false);assert.equal(ui.element('it-timeline-count').textContent,index[position].eventRefs.length+' / '+index[position].eventRefs.length);assert.equal(JSON.parse(await ui.export('json')).events.length,16);ui.document.dispatchEvent({type:'site:languagechange',detail:{language:'fr'}});assert.equal(ui.element('it-entity-selection').hidden,false);ui.element('it-entity-clear').handlers.click();assert.equal(ui.element('it-timeline-count').textContent,'16 / 16');await ui.demo('linux');assert.equal(ui.element('it-entity-selection').hidden,true);assert.equal(ui.element('it-panel-summary').hidden,false);});
