'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),{webcrypto}=require('node:crypto');
const core=require('../assets/vendor-hardening-core.js'),policy=require('../assets/firewall-review-core.js'),demos=require('../assets/vendor-hardening-demos.js');
function harness(language='en'){
 const elements=new Map(),blobs=[],events={};let pending;
 function el(id){if(!elements.has(id)){let value='';const e={files:[],dataset:{},hidden:true,handlers:{},textContent:'',innerHTML:'',setAttribute(k,v){this[k]=v;},addEventListener(k,fn){this.handlers[k]=fn;}};Object.defineProperty(e,'value',{get:()=>value,set:v=>{value=v;if(v==='')e.files=[];}});elements.set(id,e);}return elements.get(id);}
 el('vh-vendor').value='fortinet';el('vh-filter').value='all';for(const v of Object.keys(demos))el('demo-'+v).dataset.vhDemo=v;for(const v of ['policy','change'])el('mode-'+v).dataset.fcMode=v;
 const document={documentElement:{lang:language},getElementById:el,querySelectorAll:s=>s==='[data-vh-demo]'?Object.keys(demos).map(v=>el('demo-'+v)):s==='[data-fc-mode]'?['policy','change'].map(v=>el('mode-'+v)):[],addEventListener(k,fn){events[k]=fn;},dispatchEvent(e){events[e.type]?.(e);},body:{append(){}},createElement:()=>({click(){},remove(){}})};
 const context=vm.createContext({window:null,document,Event,VendorHardening:core,FirewallReview:policy,VendorHardeningDemos:demos,crypto:webcrypto,TextEncoder,TextDecoder,Uint8Array,Blob,URL:{createObjectURL:b=>{blobs.push(b);return 'blob:local';},revokeObjectURL(){}},location:{hash:'#vendor-hardening'},setTimeout:fn=>{queueMicrotask(fn);},addEventListener(k,fn){events[k]=fn;}});context.window=context;vm.runInContext(fs.readFileSync(require.resolve('../assets/vendor-hardening-ui.js'),'utf8'),context);
 return {el,blobs,context,events,async demo(v){el('demo-'+v).handlers.click();while(el('vh-status').textContent.includes('…'))await new Promise(r=>setTimeout(r,2));},review(){return el('vh-form').handlers.submit({preventDefault(){}});},async report(kind='json'){el('vh-export-'+kind).handlers.click();return blobs.at(-1)?.text();}};
}
test('All four labs render and export in EN / RO / FR with original-source hashes',async()=>{for(const language of ['en','ro','fr'])for(const vendor of Object.keys(demos)){const h=harness(language);await h.demo(vendor);assert.equal(h.el('vh-status').dataset.error,'false');assert.equal(h.el('vh-results').hidden,false);const r=JSON.parse(await h.report());assert.equal(r.synthetic,true);assert.equal(r.current.vendor,vendor);assert.ok(r.comparison.summary.fixed>=3);assert.equal(r.language,language);assert.equal(r.sources.length,2);assert.ok(r.sources.every(s=>/^[a-f0-9]{64}$/.test(s.sha256)));assert.ok(!JSON.stringify(r).includes('synthetic-secret'));const html=await h.report('html');assert.ok(html.includes('Content-Security-Policy'));assert.ok(html.includes('details open'));assert.ok(h.el('vh-store').href.includes('?lang='+language));}});
test('File bytes take precedence over pasted text and preserve exact hashes',async()=>{const h=harness();h.el('vh-vendor').value='cisco';h.el('vh-input').value='wrong pasted input';const bytes=new TextEncoder().encode(demos.cisco.after.replaceAll('\n','\r\n'));h.el('vh-file').files=[{name:'router.cfg',size:bytes.length,arrayBuffer:async()=>bytes.buffer}];await h.review();const r=JSON.parse(await h.report());const hash=Buffer.from(await webcrypto.subtle.digest('SHA-256',bytes)).toString('hex');assert.equal(r.sources[0].sha256,hash);assert.equal(r.sources[0].name,'router.cfg');assert.equal(r.current.summary.fail,0);});
test('Edited input removes stale evidence and refuses export until recomputed',async()=>{const h=harness();await h.demo('fortinet');h.el('vh-input').handlers.input();assert.equal(h.el('vh-results').hidden,true);const n=h.blobs.length;await h.report();assert.equal(h.blobs.length,n);h.el('vh-before-reference').value='different';await h.review();assert.equal(h.el('vh-status').dataset.error,'true');});
test('Clear removes inputs and rendered evidence; review mode switch restores existing form',async()=>{const h=harness();await h.demo('cisco');h.el('vh-clear').handlers.click();assert.equal(h.el('vh-input').value,'');assert.equal(h.el('vh-before').value,'');assert.equal(h.el('vh-controls').textContent,'');assert.equal(h.el('vh-results').hidden,true);h.events['fw:policymode']();assert.equal(h.el('fw-form').hidden,false);assert.equal(h.el('vendor-hardening').hidden,true);});
test('Unsafe entities and file names are escaped in HTML output',async()=>{const h=harness();h.el('vh-vendor').value='cisco';h.el('vh-input').value=demos.cisco.after.replace('line vty 0 4','line vty 0 4');h.el('vh-reference').value='<img src=x onerror=bad()>';h.el('vh-before-reference').value=h.el('vh-reference').value;h.el('vh-before').value=demos.cisco.before;await h.review();const html=await h.report('html');assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img src=x'));});
test('Language switch retranslates an existing result without recomputing evidence',async()=>{const h=harness();await h.demo('checkpoint');const before=JSON.parse(await h.report());h.events['site:languagechange']({detail:{language:'ro'}});assert.ok(h.el('vh-controls').innerHTML.includes('Gaia Telnet dezactivat explicit'));const after=JSON.parse(await h.report());assert.deepEqual(after.sources,before.sources);assert.equal(after.language,'ro');});
test('Source changes during asynchronous read cannot publish a stale result',async()=>{const h=harness();let unblock;const bytes=new TextEncoder().encode(demos.cisco.after);h.el('vh-vendor').value='cisco';h.el('vh-file').files=[{name:'r.cfg',size:bytes.length,arrayBuffer:()=>new Promise(r=>{unblock=r;})}];const p=h.review();while(!unblock)await new Promise(r=>setTimeout(r,1));h.el('vh-input').handlers.input();unblock(bytes.buffer);await p;assert.equal(h.el('vh-results').hidden,true);});
