'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process');
const core=require('../assets/vendor-hardening-core.js'),policies=require('../assets/firewall-review-core.js'),demos=require('../assets/vendor-hardening-demos.js');
const parse=(s,v,extra={})=>core.parse(s,v,{policyCore:policies,...extra});
const control=(m,k)=>m.controls.find(c=>c.check===k);
class XMLParser{
 parseFromString(s){const py="import sys,json,xml.etree.ElementTree as E\ndef dump(n): return {'name':n.tag,'attrs':n.attrib,'text':''.join(n.itertext()),'children':[dump(c) for c in n]}\ntry: print(json.dumps(dump(E.fromstring(sys.stdin.read()))))\nexcept E.ParseError: print(json.dumps({'name':'parsererror','attrs':{},'text':'invalid','children':[]}))";const p=spawnSync('python',['-c',py],{input:s,encoding:'utf8'});assert.equal(p.status,0);function node(j){const n={localName:j.name,textContent:j.text,getAttribute:k=>j.attrs[k]??null,getElementsByTagName(k){return this.children.flatMap(c=>[...(c.localName===k?[c]:[]),...c.getElementsByTagName(k)]);}};n.children=j.children.map(node);return n;}const root=node(JSON.parse(p.stdout));return {documentElement:root,getElementsByTagName:k=>[...(root.localName===k?[root]:[]),...root.getElementsByTagName(k)]};}
}
for(const vendor of Object.keys(demos))test(vendor+' lab identifies explicit issues and verifies remediation',()=>{const d=demos[vendor],a=parse(d.before,vendor),b=parse(d.after,vendor),r=core.compare(a,b,{before:d.reference,current:d.reference});assert.ok(a.summary.fail>=3);assert.equal(b.summary.fail,0);assert.ok(r.summary.fixed>=3);assert.equal(r.summary.regression,0);assert.equal(r.summary.notVerified,0);assert.equal(a.vendor,vendor);});
test('Missing settings remain unknown; disappearance cannot count as remediation',()=>{const a=parse(demos.cisco.before,'cisco'),b=parse('hostname LAB-IOS\nversion 17.6','cisco');assert.equal(b.summary.pass,0);const r=core.compare(a,b,{before:'r1',current:'r1'});assert.equal(r.summary.fixed,0);assert.ok(r.summary.notVerified>=3);});
test('New failures and lost scope are separate from fixes',()=>{const good=parse(demos.fortinet.after,'fortinet'),bad=parse(demos.fortinet.before,'fortinet');const r=core.compare(good,bad,{before:'fgt',current:'fgt'});assert.equal(r.summary.regression,9);const removed=parse('config system global\nset hostname LAB-FGT\nend','fortinet');assert.ok(core.compare(bad,removed,{before:'fgt',current:'fgt'}).rows.some(x=>x.missingAfter));});
test('Comparison rejects different vendors, absent identities and conflicting hostnames',()=>{const a=parse(demos.cisco.before,'cisco');for(const refs of [{},{current:'r',before:'r2'}])assert.throws(()=>core.compare(a,a,refs),e=>e.code==='identity');assert.throws(()=>core.compare(a,parse(demos.fortinet.after,'fortinet'),{current:'r',before:'r'}),e=>e.code==='vendorMismatch');assert.throws(()=>core.compare(a,parse(demos.cisco.after.replace('LAB-IOS','OTHER'),'cisco'),{current:'r',before:'r'}),e=>e.code==='hostnameMismatch');});
test('Fortinet default unused trusted-host slots do not override a restriction',()=>{const m=parse(demos.fortinet.after.replace('trusthost1 192.0.2.10 255.255.255.255','trusthost1 192.0.2.10 255.255.255.255\nset trusthost2 0.0.0.0 0.0.0.0'),'fortinet');assert.equal(control(m,'trustedHosts').status,'pass');assert.equal(control(parse(demos.fortinet.after.replace('192.0.2.10 255.255.255.255','999.0.2.10 255.255.255.255'),'fortinet'),'trustedHosts').status,'unknown');});
test('Fortinet distinguishes VDOMs, rejects broken exports and manager semantics',()=>{const s='config vdom\nedit A\nconfig system interface\nedit mgmt\nset allowaccess http\nnext\nend\nnext\nedit B\nconfig system interface\nedit mgmt\nset allowaccess ssh\nnext\nend\nnext\nend';const m=parse(s,'fortinet');assert.equal(m.controls.find(c=>c.scope==='vdom:A').status,'fail');assert.equal(m.controls.find(c=>c.scope==='vdom:B').status,'pass');assert.throws(()=>parse(s.slice(0,-3),'fortinet'),e=>e.code==='malformedCLI');assert.throws(()=>parse('config adom\nedit A\nnext\nend','fortinet'),e=>e.code==='managerUnsupported');});
test('FortiOS REST wrappers retain scope and only relevant fields; arrays and multiple files work',()=>{const rows=[{path:'system',name:'global',vdom:'global',status:'success',results:{hostname:'LAB',admintimeout:10,'admin-lockout-threshold':3,'admin-https-ssl-versions':'tlsv1-2 tlsv1-3'}},{path:'system',name:'admin',vdom:'global',results:[{name:'admin',password:'private-value',trusthost1:'192.0.2.10 255.255.255.255'}]}];for(const input of [JSON.stringify(rows),rows.map(x=>JSON.stringify(x))]){const m=parse(input,'fortinet');assert.equal(m.summary.pass,4);assert.ok(!JSON.stringify(m).includes('private-value'));}assert.throws(()=>parse(JSON.stringify([{...rows[0],status:'error'}]),'fortinet'),e=>e.code==='apiFailure');assert.throws(()=>parse(JSON.stringify([{policyid:1}]),'fortinet'),e=>e.code==='unsupportedJSON');});
test('Secrets are omitted from evidence and models',()=>{for(const [vendor,d]of Object.entries(demos)){const m=parse(d.before,vendor);assert.ok(!JSON.stringify(m).includes('synthetic-secret'));}const s=demos.fortinet.before.replace('set trusthost1','set password "very-secret-password"\nset trusthost1');assert.ok(!JSON.stringify(parse(s,'fortinet')).includes('very-secret-password'));});
test('Unsupported TLS values stay unknown, insecure versions fail',()=>{for(const [v,status]of [['tlsv1-9','unknown'],['tlsv1-1 tlsv1-3','fail'],['tlsv1-2 tlsv1-3','pass']])assert.equal(control(parse(demos.fortinet.before.replace('tlsv1-0 tlsv1-2',v),'fortinet'),'tls').status,status);});
test('Cisco VTY ranges have separate evidence and fractional timeouts',()=>{const s=demos.cisco.after.replace('end','line vty 5 15\n transport input telnet\n exec-timeout 15 1\nend');const m=parse(s,'cisco');assert.equal(m.controls.filter(x=>x.check==='vtyTransport').length,2);assert.equal(m.controls.find(x=>x.entity==='line vty 5 15'&&x.check==='idle').status,'fail');assert.ok(m.controls.find(x=>x.entity==='line vty 0 4'&&x.check==='vtyACL').reason==='referenceOnly');});
test('Cisco excludes ASA syntax and does not expose SNMP communities',()=>{assert.throws(()=>parse('ASA Version 9.18\nhostname ASA\naccess-group OUTSIDE in interface outside','cisco'),e=>e.code==='ciscoPlatform');const s=demos.cisco.before.replace('synthetic-secret','REAL-COMMUNITY');const m=parse(s,'cisco');assert.equal(control(m,'snmp').status,'fail');assert.ok(!JSON.stringify(m).includes('REAL-COMMUNITY'));});
test('PAN-OS XML supplies the same six settings as CLI without inferring defaults',()=>{const xml='<config><deviceconfig><system><hostname>LAB-PA</hostname><service><disable-http>yes</disable-http><disable-telnet>yes</disable-telnet></service><permitted-ip><entry name="192.0.2.10/32"/></permitted-ip></system></deviceconfig><mgt-config><users><entry name="lab-admin"><phash>hidden</phash></entry></users></mgt-config><vsys><entry name="vsys1"><rulebase><security><rules><entry name="Lab-Web"><action>allow</action><log-end>yes</log-end><profile-setting><group><member>Lab-Protection</member></group></profile-setting><log-setting>Lab-Forwarding</log-setting></entry></rules></security></rulebase></entry></vsys></config>';const m=parse(xml,'paloalto',{XMLParser});assert.equal(m.summary.pass,6);assert.equal(m.summary.unknown,0);assert.ok(!JSON.stringify(m).includes('hidden'));const missing=parse('<config><deviceconfig><system><hostname>LAB-PA</hostname></system></deviceconfig></config>','paloalto',{XMLParser});assert.equal(missing.summary.pass,0);assert.equal(missing.summary.unknown,3);});
test('PAN-OS scope and UUID are preserved; entity declarations and malformed CLI fail',()=>{const xml='<config><shared><pre-rulebase><security><rules><entry name="A" uuid="u-1"><log-end>no</log-end></entry></rules></security></pre-rulebase></shared></config>';const m=parse(xml,'paloalto',{XMLParser});assert.ok(m.controls.some(c=>c.entity==='u-1'&&c.scope==='shared/pre-rulebase/security/rules'));assert.throws(()=>parse('<!DOCTYPE config><config/>','paloalto',{XMLParser}),e=>e.code==='unsafeXML');assert.throws(()=>parse('set vsys "bad','paloalto'),e=>e.code==='malformedCLI');assert.throws(()=>parse('delete deviceconfig system service','paloalto'),e=>e.code==='malformedCLI');});
test('Conflicting explicit values do not silently overwrite evidence',()=>{for(const [s,v]of [[demos.cisco.before+'\nip ssh version 2','cisco'],[demos.checkpoint.before+'\nset snmp agent-version v3-Only','checkpoint'],[demos.fortinet.before.replace('set admintimeout 0','set admintimeout 0\nset admintimeout 5'),'fortinet']])assert.throws(()=>parse(s,v),e=>e.code==='conflictingData');});
const cp=(track='None')=>({uid:'layer-id',name:'Lab',from:1,to:1,total:1,rulebase:[{type:'access-rule',uid:'rule-id',name:'Cleanup','rule-number':1,enabled:true,source:[{type:'CpmiAnyObject',name:'Any'}],destination:[{type:'CpmiAnyObject',name:'Any'}],service:[{type:'CpmiAnyObject',name:'Any'}],time:[{type:'CpmiAnyObject',name:'Any'}],vpn:[{type:'CpmiAnyObject',name:'Any'}],content:[{type:'CpmiAnyObject',name:'Any'}],action:{name:'Drop'},track:{type:{name:track}}}]});
test('Check Point layer ending is checked only with explicit full pagination metadata',()=>{let j=cp();let m=parse(JSON.stringify(j),'checkpoint');assert.equal(control(m,'cleanup').status,'pass');assert.equal(control(m,'policyLog').status,'fail');delete j.total;m=parse(JSON.stringify(j),'checkpoint');assert.equal(control(m,'cleanup').status,'unknown');j=cp();j.total=2;assert.equal(control(parse(JSON.stringify(j),'checkpoint'),'cleanup').status,'unknown');});
test('Check Point UID resolution supports logging and a Gaia file in the same review',()=>{const j=cp();j.rulebase[0].track={type:'11111111-1111-1111-1111-111111111111'};j['objects-dictionary']=[{uid:'11111111-1111-1111-1111-111111111111',name:'Log',type:'Track'}];const m=parse([JSON.stringify(j),demos.checkpoint.after],'checkpoint');assert.equal(control(m,'policyLog').status,'pass');assert.equal(m.formats.length,2);assert.equal(m.summary.fail,0);});
test('Check Point inline layers and restricted VPN/time cannot be called cleanup',()=>{for(const mutate of [j=>j.rulebase[0]['inline-layer']='child',j=>j.rulebase[0].vpn=[{name:'VPN-A'}],j=>j.rulebase[0].time=[{name:'Work-hours'}]]){const j=cp();mutate(j);assert.equal(control(parse(JSON.stringify(j),'checkpoint'),'cleanup').status,'unknown');}});
test('Hardening parser enforces the byte limit and rejects unsupported formats',()=>{assert.throws(()=>parse('x'.repeat(core.MAX_BYTES+1),'cisco'),e=>e.code==='tooLarge');assert.throws(()=>parse('','cisco'),e=>e.code==='empty');assert.throws(()=>parse('hostname x','unknown'),e=>e.code==='vendor');assert.throws(()=>parse('{"schema":"report"}','fortinet'),e=>e.code==='unsupportedJSON');});
